name: Build Flet APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install flet==0.19.0
          pip install -r requirements.txt

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      # هذه الخطوة هي المسؤولة عن تهيئة المجلد وتغيير الاسم بالعربي
      - name: Configure App Name
        run: |
          mkdir -p android/app/src/main/res/values
          echo '<?xml version="1.0" encoding="utf-8"?>' > android/app/src/main/res/values/strings.xml
          echo '<resources>' >> android/app/src/main/res/values/strings.xml
          echo '    <string name="app_name">تطبيق الجمعة</string>' >> android/app/src/main/res/values/strings.xml
          echo '</resources>' >> android/app/src/main/res/values/strings.xml

      - name: Build APK
        run: |
          flet build apk
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/app-release.apk
